# TL;DR: YOU SHOULD DELETE THIS FILE
#
# This file iwas generated by Cucumber-Rails and is only here to get you a head start
# These step definitions are thin wrappers around the Capybara/Webrat API that lets you
# visit pages, interact with widgets and make assertions about page content.
#
# If you use these step definitions as basis for your features you will quickly end up
# with features that are:
#
# * Hard to maintain
# * Verbose to read
#
# A much better approach is to write your own higher level step definitions, following
# the advice in the following blog posts:
#
# * http://benmabey.com/2008/05/19/imperative-vs-declarative-scenarios-in-user-stories.html
# * http://dannorth.net/2011/01/31/whose-domain-is-it-anyway/
# * http://elabs.se/blog/15-you-re-cuking-it-wrong 
#

require 'cucumber/rails'

# Capybara defaults to XPath selectors rather than Webrat's default of CSS3. In
# order to ease the transition to Capybara we set the default here. If you'd
# prefer to use XPath just remove this line and adjust any selectors in your
# steps to use the XPath syntax.
Capybara.default_selector = :css

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how 
# your application behaves in the production environment, where an error page will 
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Remove this line if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
DatabaseCleaner.strategy = :transaction

Before do
#Create Basic Menusets
Menuset.create(:name=>"Header",:description=>"Header Menu for RlingCMS")
Menuset.create(:name=>"Footer",:description=>"Footer Menu for RlingCMS")

#Create Roles
Role.create(:role_type=>"Anonymous",:is_deletable=>false)
Role.create(:role_type=>"User",:is_deletable=>false)
Role.create(:role_type=>"Administrator",:is_deletable=>false)

#Create Login Settings
Setting.create(:name=>"allow_user_register_user",:desc_text=>"Should the System allow users to sign up to the website on their own. i.e. Should there be a sign up link for the user to execute",:setting_type=>"boolean",:setting_value=>"false")
Setting.create(:name=>"allow_admin_register_user",:desc_text=>"Should the System allow administrators to self register users to the website",:setting_type=>"boolean",:setting_value=>"true")
Setting.create(:name=>"send_welcome_email",:desc_text=>"If a user is registered, should there be a welcome email sent to the user on registration",:setting_type=>"boolean",:setting_value=>"false")
Setting.create(:name=>"is_login_type_email",:desc_text=>"Should the login to the website be done using the login or by using the email address of the user",:setting_type=>"boolean",:setting_value=>"false")
Setting.create(:name=>"user_activation_required_on_user",:desc_text=>"Should the System send activation email when the user registers into the website",:setting_type=>"boolean",:setting_value=>"false")
Setting.create(:name=>"user_activation_required_on_admin",:desc_text=>"Should the System send activation email when the admin registers the user using admin panel in the website",:setting_type=>"boolean",:setting_value=>"false")
Setting.create(:name=>"site_url",:desc_text=>"URL of the Site that is required to go out as external links. e.g. in emails, on pages, etc.,",:setting_type=>"string",:setting_value=>"http://localhost:3000")
Setting.create(:name=>"smtp_settings",:desc_text=>"SMTP Configuration settings required to send emails from the CMS",:setting_type=>"string",:setting_value=>"address:smtp.rlingcms.com;port:25;domain:mail.rlingcms.com;authentication:plain;user_name:myusername;password:mypassword;")

#Create Mailer Settings
Mailer.create(:handle=>"welcome",:subject=>"Welcome Mail",:body=>"Welcome to Rling CMS. You have been registered successfully",:is_deletable=>"false",:allowable_tags=>"User")
Mailer.create(:handle=>"activation",:subject=>"Activation Mail",:body=>"Welcome to Rling CMS. Click on the activation link below to activate your account",:is_deletable=>"false",:allowable_tags=>"User")
Mailer.create(:handle=>"forgot",:subject=>"Reset Password",:body=>"Click on the link below to reset your password",:is_deletable=>"false",:allowable_tags=>"User")
end


