source 'http://rubygems.org'

gem 'rails', '3.0.5'
gem 'mysql', '2.8.1'
gem 'rspec-rails'
gem 'rspec'
gem 'rspec-core'
gem 'rspec-expectations'
gem 'rspec-mocks'
gem 'autotest'
gem 'factory_girl'
gem 'acts_as_tree'
gem 'ckeditor'
