require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CategorysetsController do

  def mock_categoryset(stubs={})
    @mock_categoryset ||= mock_model(Categoryset, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all categorysets as @categorysets" do
      Categoryset.stub(:all) { [mock_categoryset] }
      get :index
      assigns(:categorysets).should eq([mock_categoryset])
    end
  end

  describe "GET show" do
    it "assigns the requested categoryset as @categoryset" do
      Categoryset.stub(:find).with("37") { mock_categoryset }
      get :show, :id => "37"
      assigns(:categoryset).should be(mock_categoryset)
    end
  end

  describe "GET new" do
    it "assigns a new categoryset as @categoryset" do
      Categoryset.stub(:new) { mock_categoryset }
      get :new
      assigns(:categoryset).should be(mock_categoryset)
    end
  end

  describe "GET edit" do
    it "assigns the requested categoryset as @categoryset" do
      Categoryset.stub(:find).with("37") { mock_categoryset }
      get :edit, :id => "37"
      assigns(:categoryset).should be(mock_categoryset)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created categoryset as @categoryset" do
        Categoryset.stub(:new).with({'these' => 'params'}) { mock_categoryset(:save => true) }
        post :create, :categoryset => {'these' => 'params'}
        assigns(:categoryset).should be(mock_categoryset)
      end

      it "redirects to the created categoryset" do
        Categoryset.stub(:new) { mock_categoryset(:save => true) }
        post :create, :categoryset => {}
        response.should redirect_to(categoryset_url(mock_categoryset))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved categoryset as @categoryset" do
        Categoryset.stub(:new).with({'these' => 'params'}) { mock_categoryset(:save => false) }
        post :create, :categoryset => {'these' => 'params'}
        assigns(:categoryset).should be(mock_categoryset)
      end

      it "re-renders the 'new' template" do
        Categoryset.stub(:new) { mock_categoryset(:save => false) }
        post :create, :categoryset => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested categoryset" do
        Categoryset.stub(:find).with("37") { mock_categoryset }
        mock_categoryset.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :categoryset => {'these' => 'params'}
      end

      it "assigns the requested categoryset as @categoryset" do
        Categoryset.stub(:find) { mock_categoryset(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:categoryset).should be(mock_categoryset)
      end

      it "redirects to the categoryset" do
        Categoryset.stub(:find) { mock_categoryset(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(categoryset_url(mock_categoryset))
      end
    end

    describe "with invalid params" do
      it "assigns the categoryset as @categoryset" do
        Categoryset.stub(:find) { mock_categoryset(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:categoryset).should be(mock_categoryset)
      end

      it "re-renders the 'edit' template" do
        Categoryset.stub(:find) { mock_categoryset(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested categoryset" do
      Categoryset.stub(:find).with("37") { mock_categoryset }
      mock_categoryset.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the categorysets list" do
      Categoryset.stub(:find) { mock_categoryset }
      delete :destroy, :id => "1"
      response.should redirect_to(categorysets_url)
    end
  end

end
