require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CommentSubmissionsController do

  def mock_comment_submission(stubs={})
    @mock_comment_submission ||= mock_model(CommentSubmission, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all comment_submissions as @comment_submissions" do
      CommentSubmission.stub(:all) { [mock_comment_submission] }
      get :index
      assigns(:comment_submissions).should eq([mock_comment_submission])
    end
  end

  describe "GET show" do
    it "assigns the requested comment_submission as @comment_submission" do
      CommentSubmission.stub(:find).with("37") { mock_comment_submission }
      get :show, :id => "37"
      assigns(:comment_submission).should be(mock_comment_submission)
    end
  end

  describe "GET new" do
    it "assigns a new comment_submission as @comment_submission" do
      CommentSubmission.stub(:new) { mock_comment_submission }
      get :new
      assigns(:comment_submission).should be(mock_comment_submission)
    end
  end

  describe "GET edit" do
    it "assigns the requested comment_submission as @comment_submission" do
      CommentSubmission.stub(:find).with("37") { mock_comment_submission }
      get :edit, :id => "37"
      assigns(:comment_submission).should be(mock_comment_submission)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created comment_submission as @comment_submission" do
        CommentSubmission.stub(:new).with({'these' => 'params'}) { mock_comment_submission(:save => true) }
        post :create, :comment_submission => {'these' => 'params'}
        assigns(:comment_submission).should be(mock_comment_submission)
      end

      it "redirects to the created comment_submission" do
        CommentSubmission.stub(:new) { mock_comment_submission(:save => true) }
        post :create, :comment_submission => {}
        response.should redirect_to(comment_submission_url(mock_comment_submission))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved comment_submission as @comment_submission" do
        CommentSubmission.stub(:new).with({'these' => 'params'}) { mock_comment_submission(:save => false) }
        post :create, :comment_submission => {'these' => 'params'}
        assigns(:comment_submission).should be(mock_comment_submission)
      end

      it "re-renders the 'new' template" do
        CommentSubmission.stub(:new) { mock_comment_submission(:save => false) }
        post :create, :comment_submission => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested comment_submission" do
        CommentSubmission.stub(:find).with("37") { mock_comment_submission }
        mock_comment_submission.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :comment_submission => {'these' => 'params'}
      end

      it "assigns the requested comment_submission as @comment_submission" do
        CommentSubmission.stub(:find) { mock_comment_submission(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:comment_submission).should be(mock_comment_submission)
      end

      it "redirects to the comment_submission" do
        CommentSubmission.stub(:find) { mock_comment_submission(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(comment_submission_url(mock_comment_submission))
      end
    end

    describe "with invalid params" do
      it "assigns the comment_submission as @comment_submission" do
        CommentSubmission.stub(:find) { mock_comment_submission(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:comment_submission).should be(mock_comment_submission)
      end

      it "re-renders the 'edit' template" do
        CommentSubmission.stub(:find) { mock_comment_submission(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested comment_submission" do
      CommentSubmission.stub(:find).with("37") { mock_comment_submission }
      mock_comment_submission.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the comment_submissions list" do
      CommentSubmission.stub(:find) { mock_comment_submission }
      delete :destroy, :id => "1"
      response.should redirect_to(comment_submissions_url)
    end
  end

end
