require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FormComponentsController do

  def mock_form_component(stubs={})
    @mock_form_component ||= mock_model(FormComponent, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all form_components as @form_components" do
      FormComponent.stub(:all) { [mock_form_component] }
      get :index
      assigns(:form_components).should eq([mock_form_component])
    end
  end

  describe "GET show" do
    it "assigns the requested form_component as @form_component" do
      FormComponent.stub(:find).with("37") { mock_form_component }
      get :show, :id => "37"
      assigns(:form_component).should be(mock_form_component)
    end
  end

  describe "GET new" do
    it "assigns a new form_component as @form_component" do
      FormComponent.stub(:new) { mock_form_component }
      get :new
      assigns(:form_component).should be(mock_form_component)
    end
  end

  describe "GET edit" do
    it "assigns the requested form_component as @form_component" do
      FormComponent.stub(:find).with("37") { mock_form_component }
      get :edit, :id => "37"
      assigns(:form_component).should be(mock_form_component)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created form_component as @form_component" do
        FormComponent.stub(:new).with({'these' => 'params'}) { mock_form_component(:save => true) }
        post :create, :form_component => {'these' => 'params'}
        assigns(:form_component).should be(mock_form_component)
      end

      it "redirects to the created form_component" do
        FormComponent.stub(:new) { mock_form_component(:save => true) }
        post :create, :form_component => {}
        response.should redirect_to(form_component_url(mock_form_component))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved form_component as @form_component" do
        FormComponent.stub(:new).with({'these' => 'params'}) { mock_form_component(:save => false) }
        post :create, :form_component => {'these' => 'params'}
        assigns(:form_component).should be(mock_form_component)
      end

      it "re-renders the 'new' template" do
        FormComponent.stub(:new) { mock_form_component(:save => false) }
        post :create, :form_component => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested form_component" do
        FormComponent.stub(:find).with("37") { mock_form_component }
        mock_form_component.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :form_component => {'these' => 'params'}
      end

      it "assigns the requested form_component as @form_component" do
        FormComponent.stub(:find) { mock_form_component(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:form_component).should be(mock_form_component)
      end

      it "redirects to the form_component" do
        FormComponent.stub(:find) { mock_form_component(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(form_component_url(mock_form_component))
      end
    end

    describe "with invalid params" do
      it "assigns the form_component as @form_component" do
        FormComponent.stub(:find) { mock_form_component(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:form_component).should be(mock_form_component)
      end

      it "re-renders the 'edit' template" do
        FormComponent.stub(:find) { mock_form_component(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested form_component" do
      FormComponent.stub(:find).with("37") { mock_form_component }
      mock_form_component.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the form_components list" do
      FormComponent.stub(:find) { mock_form_component }
      delete :destroy, :id => "1"
      response.should redirect_to(form_components_url)
    end
  end

end
