require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MailersController do

  def mock_mailer(stubs={})
    @mock_mailer ||= mock_model(Mailer, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all mailers as @mailers" do
      Mailer.stub(:all) { [mock_mailer] }
      get :index
      assigns(:mailers).should eq([mock_mailer])
    end
  end

  describe "GET show" do
    it "assigns the requested mailer as @mailer" do
      Mailer.stub(:find).with("37") { mock_mailer }
      get :show, :id => "37"
      assigns(:mailer).should be(mock_mailer)
    end
  end

  describe "GET new" do
    it "assigns a new mailer as @mailer" do
      Mailer.stub(:new) { mock_mailer }
      get :new
      assigns(:mailer).should be(mock_mailer)
    end
  end

  describe "GET edit" do
    it "assigns the requested mailer as @mailer" do
      Mailer.stub(:find).with("37") { mock_mailer }
      get :edit, :id => "37"
      assigns(:mailer).should be(mock_mailer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created mailer as @mailer" do
        Mailer.stub(:new).with({'these' => 'params'}) { mock_mailer(:save => true) }
        post :create, :mailer => {'these' => 'params'}
        assigns(:mailer).should be(mock_mailer)
      end

      it "redirects to the created mailer" do
        Mailer.stub(:new) { mock_mailer(:save => true) }
        post :create, :mailer => {}
        response.should redirect_to(mailer_url(mock_mailer))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mailer as @mailer" do
        Mailer.stub(:new).with({'these' => 'params'}) { mock_mailer(:save => false) }
        post :create, :mailer => {'these' => 'params'}
        assigns(:mailer).should be(mock_mailer)
      end

      it "re-renders the 'new' template" do
        Mailer.stub(:new) { mock_mailer(:save => false) }
        post :create, :mailer => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mailer" do
        Mailer.stub(:find).with("37") { mock_mailer }
        mock_mailer.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :mailer => {'these' => 'params'}
      end

      it "assigns the requested mailer as @mailer" do
        Mailer.stub(:find) { mock_mailer(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:mailer).should be(mock_mailer)
      end

      it "redirects to the mailer" do
        Mailer.stub(:find) { mock_mailer(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(mailer_url(mock_mailer))
      end
    end

    describe "with invalid params" do
      it "assigns the mailer as @mailer" do
        Mailer.stub(:find) { mock_mailer(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:mailer).should be(mock_mailer)
      end

      it "re-renders the 'edit' template" do
        Mailer.stub(:find) { mock_mailer(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mailer" do
      Mailer.stub(:find).with("37") { mock_mailer }
      mock_mailer.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the mailers list" do
      Mailer.stub(:find) { mock_mailer }
      delete :destroy, :id => "1"
      response.should redirect_to(mailers_url)
    end
  end

end
