require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MenusetsController do

  def mock_menuset(stubs={})
    @mock_menuset ||= mock_model(Menuset, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all menusets as @menusets" do
      Menuset.stub(:all) { [mock_menuset] }
      get :index
      assigns(:menusets).should eq([mock_menuset])
    end
  end

  describe "GET show" do
    it "assigns the requested menuset as @menuset" do
      Menuset.stub(:find).with("37") { mock_menuset }
      get :show, :id => "37"
      assigns(:menuset).should be(mock_menuset)
    end
  end

  describe "GET new" do
    it "assigns a new menuset as @menuset" do
      Menuset.stub(:new) { mock_menuset }
      get :new
      assigns(:menuset).should be(mock_menuset)
    end
  end

  describe "GET edit" do
    it "assigns the requested menuset as @menuset" do
      Menuset.stub(:find).with("37") { mock_menuset }
      get :edit, :id => "37"
      assigns(:menuset).should be(mock_menuset)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created menuset as @menuset" do
        Menuset.stub(:new).with({'these' => 'params'}) { mock_menuset(:save => true) }
        post :create, :menuset => {'these' => 'params'}
        assigns(:menuset).should be(mock_menuset)
      end

      it "redirects to the created menuset" do
        Menuset.stub(:new) { mock_menuset(:save => true) }
        post :create, :menuset => {}
        response.should redirect_to(menuset_url(mock_menuset))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved menuset as @menuset" do
        Menuset.stub(:new).with({'these' => 'params'}) { mock_menuset(:save => false) }
        post :create, :menuset => {'these' => 'params'}
        assigns(:menuset).should be(mock_menuset)
      end

      it "re-renders the 'new' template" do
        Menuset.stub(:new) { mock_menuset(:save => false) }
        post :create, :menuset => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested menuset" do
        Menuset.stub(:find).with("37") { mock_menuset }
        mock_menuset.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :menuset => {'these' => 'params'}
      end

      it "assigns the requested menuset as @menuset" do
        Menuset.stub(:find) { mock_menuset(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:menuset).should be(mock_menuset)
      end

      it "redirects to the menuset" do
        Menuset.stub(:find) { mock_menuset(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(menuset_url(mock_menuset))
      end
    end

    describe "with invalid params" do
      it "assigns the menuset as @menuset" do
        Menuset.stub(:find) { mock_menuset(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:menuset).should be(mock_menuset)
      end

      it "re-renders the 'edit' template" do
        Menuset.stub(:find) { mock_menuset(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested menuset" do
      Menuset.stub(:find).with("37") { mock_menuset }
      mock_menuset.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the menusets list" do
      Menuset.stub(:find) { mock_menuset }
      delete :destroy, :id => "1"
      response.should redirect_to(menusets_url)
    end
  end

end
