require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ModelComponentsController do

  def mock_model_component(stubs={})
    @mock_model_component ||= mock_model(ModelComponent, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all model_components as @model_components" do
      ModelComponent.stub(:all) { [mock_model_component] }
      get :index
      assigns(:model_components).should eq([mock_model_component])
    end
  end

  describe "GET show" do
    it "assigns the requested model_component as @model_component" do
      ModelComponent.stub(:find).with("37") { mock_model_component }
      get :show, :id => "37"
      assigns(:model_component).should be(mock_model_component)
    end
  end

  describe "GET new" do
    it "assigns a new model_component as @model_component" do
      ModelComponent.stub(:new) { mock_model_component }
      get :new
      assigns(:model_component).should be(mock_model_component)
    end
  end

  describe "GET edit" do
    it "assigns the requested model_component as @model_component" do
      ModelComponent.stub(:find).with("37") { mock_model_component }
      get :edit, :id => "37"
      assigns(:model_component).should be(mock_model_component)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created model_component as @model_component" do
        ModelComponent.stub(:new).with({'these' => 'params'}) { mock_model_component(:save => true) }
        post :create, :model_component => {'these' => 'params'}
        assigns(:model_component).should be(mock_model_component)
      end

      it "redirects to the created model_component" do
        ModelComponent.stub(:new) { mock_model_component(:save => true) }
        post :create, :model_component => {}
        response.should redirect_to(model_component_url(mock_model_component))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved model_component as @model_component" do
        ModelComponent.stub(:new).with({'these' => 'params'}) { mock_model_component(:save => false) }
        post :create, :model_component => {'these' => 'params'}
        assigns(:model_component).should be(mock_model_component)
      end

      it "re-renders the 'new' template" do
        ModelComponent.stub(:new) { mock_model_component(:save => false) }
        post :create, :model_component => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested model_component" do
        ModelComponent.stub(:find).with("37") { mock_model_component }
        mock_model_component.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :model_component => {'these' => 'params'}
      end

      it "assigns the requested model_component as @model_component" do
        ModelComponent.stub(:find) { mock_model_component(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:model_component).should be(mock_model_component)
      end

      it "redirects to the model_component" do
        ModelComponent.stub(:find) { mock_model_component(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(model_component_url(mock_model_component))
      end
    end

    describe "with invalid params" do
      it "assigns the model_component as @model_component" do
        ModelComponent.stub(:find) { mock_model_component(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:model_component).should be(mock_model_component)
      end

      it "re-renders the 'edit' template" do
        ModelComponent.stub(:find) { mock_model_component(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested model_component" do
      ModelComponent.stub(:find).with("37") { mock_model_component }
      mock_model_component.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the model_components list" do
      ModelComponent.stub(:find) { mock_model_component }
      delete :destroy, :id => "1"
      response.should redirect_to(model_components_url)
    end
  end

end
