require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ModelSubmissionsController do

  def mock_model_submission(stubs={})
    @mock_model_submission ||= mock_model(ModelSubmission, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all model_submissions as @model_submissions" do
      ModelSubmission.stub(:all) { [mock_model_submission] }
      get :index
      assigns(:model_submissions).should eq([mock_model_submission])
    end
  end

  describe "GET show" do
    it "assigns the requested model_submission as @model_submission" do
      ModelSubmission.stub(:find).with("37") { mock_model_submission }
      get :show, :id => "37"
      assigns(:model_submission).should be(mock_model_submission)
    end
  end

  describe "GET new" do
    it "assigns a new model_submission as @model_submission" do
      ModelSubmission.stub(:new) { mock_model_submission }
      get :new
      assigns(:model_submission).should be(mock_model_submission)
    end
  end

  describe "GET edit" do
    it "assigns the requested model_submission as @model_submission" do
      ModelSubmission.stub(:find).with("37") { mock_model_submission }
      get :edit, :id => "37"
      assigns(:model_submission).should be(mock_model_submission)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created model_submission as @model_submission" do
        ModelSubmission.stub(:new).with({'these' => 'params'}) { mock_model_submission(:save => true) }
        post :create, :model_submission => {'these' => 'params'}
        assigns(:model_submission).should be(mock_model_submission)
      end

      it "redirects to the created model_submission" do
        ModelSubmission.stub(:new) { mock_model_submission(:save => true) }
        post :create, :model_submission => {}
        response.should redirect_to(model_submission_url(mock_model_submission))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved model_submission as @model_submission" do
        ModelSubmission.stub(:new).with({'these' => 'params'}) { mock_model_submission(:save => false) }
        post :create, :model_submission => {'these' => 'params'}
        assigns(:model_submission).should be(mock_model_submission)
      end

      it "re-renders the 'new' template" do
        ModelSubmission.stub(:new) { mock_model_submission(:save => false) }
        post :create, :model_submission => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested model_submission" do
        ModelSubmission.stub(:find).with("37") { mock_model_submission }
        mock_model_submission.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :model_submission => {'these' => 'params'}
      end

      it "assigns the requested model_submission as @model_submission" do
        ModelSubmission.stub(:find) { mock_model_submission(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:model_submission).should be(mock_model_submission)
      end

      it "redirects to the model_submission" do
        ModelSubmission.stub(:find) { mock_model_submission(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(model_submission_url(mock_model_submission))
      end
    end

    describe "with invalid params" do
      it "assigns the model_submission as @model_submission" do
        ModelSubmission.stub(:find) { mock_model_submission(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:model_submission).should be(mock_model_submission)
      end

      it "re-renders the 'edit' template" do
        ModelSubmission.stub(:find) { mock_model_submission(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested model_submission" do
      ModelSubmission.stub(:find).with("37") { mock_model_submission }
      mock_model_submission.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the model_submissions list" do
      ModelSubmission.stub(:find) { mock_model_submission }
      delete :destroy, :id => "1"
      response.should redirect_to(model_submissions_url)
    end
  end

end
