require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ObjectModelsController do

  def mock_object_model(stubs={})
    @mock_object_model ||= mock_model(ObjectModel, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all object_models as @object_models" do
      ObjectModel.stub(:all) { [mock_object_model] }
      get :index
      assigns(:object_models).should eq([mock_object_model])
    end
  end

  describe "GET show" do
    it "assigns the requested object_model as @object_model" do
      ObjectModel.stub(:find).with("37") { mock_object_model }
      get :show, :id => "37"
      assigns(:object_model).should be(mock_object_model)
    end
  end

  describe "GET new" do
    it "assigns a new object_model as @object_model" do
      ObjectModel.stub(:new) { mock_object_model }
      get :new
      assigns(:object_model).should be(mock_object_model)
    end
  end

  describe "GET edit" do
    it "assigns the requested object_model as @object_model" do
      ObjectModel.stub(:find).with("37") { mock_object_model }
      get :edit, :id => "37"
      assigns(:object_model).should be(mock_object_model)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created object_model as @object_model" do
        ObjectModel.stub(:new).with({'these' => 'params'}) { mock_object_model(:save => true) }
        post :create, :object_model => {'these' => 'params'}
        assigns(:object_model).should be(mock_object_model)
      end

      it "redirects to the created object_model" do
        ObjectModel.stub(:new) { mock_object_model(:save => true) }
        post :create, :object_model => {}
        response.should redirect_to(object_model_url(mock_object_model))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved object_model as @object_model" do
        ObjectModel.stub(:new).with({'these' => 'params'}) { mock_object_model(:save => false) }
        post :create, :object_model => {'these' => 'params'}
        assigns(:object_model).should be(mock_object_model)
      end

      it "re-renders the 'new' template" do
        ObjectModel.stub(:new) { mock_object_model(:save => false) }
        post :create, :object_model => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested object_model" do
        ObjectModel.stub(:find).with("37") { mock_object_model }
        mock_object_model.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :object_model => {'these' => 'params'}
      end

      it "assigns the requested object_model as @object_model" do
        ObjectModel.stub(:find) { mock_object_model(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:object_model).should be(mock_object_model)
      end

      it "redirects to the object_model" do
        ObjectModel.stub(:find) { mock_object_model(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(object_model_url(mock_object_model))
      end
    end

    describe "with invalid params" do
      it "assigns the object_model as @object_model" do
        ObjectModel.stub(:find) { mock_object_model(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:object_model).should be(mock_object_model)
      end

      it "re-renders the 'edit' template" do
        ObjectModel.stub(:find) { mock_object_model(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested object_model" do
      ObjectModel.stub(:find).with("37") { mock_object_model }
      mock_object_model.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the object_models list" do
      ObjectModel.stub(:find) { mock_object_model }
      delete :destroy, :id => "1"
      response.should redirect_to(object_models_url)
    end
  end

end
