require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PageletsController do

  def mock_pagelet(stubs={})
    @mock_pagelet ||= mock_model(Pagelet, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all pagelets as @pagelets" do
      Pagelet.stub(:all) { [mock_pagelet] }
      get :index
      assigns(:pagelets).should eq([mock_pagelet])
    end
  end

  describe "GET show" do
    it "assigns the requested pagelet as @pagelet" do
      Pagelet.stub(:find).with("37") { mock_pagelet }
      get :show, :id => "37"
      assigns(:pagelet).should be(mock_pagelet)
    end
  end

  describe "GET new" do
    it "assigns a new pagelet as @pagelet" do
      Pagelet.stub(:new) { mock_pagelet }
      get :new
      assigns(:pagelet).should be(mock_pagelet)
    end
  end

  describe "GET edit" do
    it "assigns the requested pagelet as @pagelet" do
      Pagelet.stub(:find).with("37") { mock_pagelet }
      get :edit, :id => "37"
      assigns(:pagelet).should be(mock_pagelet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created pagelet as @pagelet" do
        Pagelet.stub(:new).with({'these' => 'params'}) { mock_pagelet(:save => true) }
        post :create, :pagelet => {'these' => 'params'}
        assigns(:pagelet).should be(mock_pagelet)
      end

      it "redirects to the created pagelet" do
        Pagelet.stub(:new) { mock_pagelet(:save => true) }
        post :create, :pagelet => {}
        response.should redirect_to(pagelet_url(mock_pagelet))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pagelet as @pagelet" do
        Pagelet.stub(:new).with({'these' => 'params'}) { mock_pagelet(:save => false) }
        post :create, :pagelet => {'these' => 'params'}
        assigns(:pagelet).should be(mock_pagelet)
      end

      it "re-renders the 'new' template" do
        Pagelet.stub(:new) { mock_pagelet(:save => false) }
        post :create, :pagelet => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pagelet" do
        Pagelet.stub(:find).with("37") { mock_pagelet }
        mock_pagelet.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :pagelet => {'these' => 'params'}
      end

      it "assigns the requested pagelet as @pagelet" do
        Pagelet.stub(:find) { mock_pagelet(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:pagelet).should be(mock_pagelet)
      end

      it "redirects to the pagelet" do
        Pagelet.stub(:find) { mock_pagelet(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(pagelet_url(mock_pagelet))
      end
    end

    describe "with invalid params" do
      it "assigns the pagelet as @pagelet" do
        Pagelet.stub(:find) { mock_pagelet(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:pagelet).should be(mock_pagelet)
      end

      it "re-renders the 'edit' template" do
        Pagelet.stub(:find) { mock_pagelet(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pagelet" do
      Pagelet.stub(:find).with("37") { mock_pagelet }
      mock_pagelet.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the pagelets list" do
      Pagelet.stub(:find) { mock_pagelet }
      delete :destroy, :id => "1"
      response.should redirect_to(pagelets_url)
    end
  end

end
