require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PageVariableSettingsController do

  def mock_page_variable_setting(stubs={})
    @mock_page_variable_setting ||= mock_model(PageVariableSetting, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all page_variable_settings as @page_variable_settings" do
      PageVariableSetting.stub(:all) { [mock_page_variable_setting] }
      get :index
      assigns(:page_variable_settings).should eq([mock_page_variable_setting])
    end
  end

  describe "GET show" do
    it "assigns the requested page_variable_setting as @page_variable_setting" do
      PageVariableSetting.stub(:find).with("37") { mock_page_variable_setting }
      get :show, :id => "37"
      assigns(:page_variable_setting).should be(mock_page_variable_setting)
    end
  end

  describe "GET new" do
    it "assigns a new page_variable_setting as @page_variable_setting" do
      PageVariableSetting.stub(:new) { mock_page_variable_setting }
      get :new
      assigns(:page_variable_setting).should be(mock_page_variable_setting)
    end
  end

  describe "GET edit" do
    it "assigns the requested page_variable_setting as @page_variable_setting" do
      PageVariableSetting.stub(:find).with("37") { mock_page_variable_setting }
      get :edit, :id => "37"
      assigns(:page_variable_setting).should be(mock_page_variable_setting)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created page_variable_setting as @page_variable_setting" do
        PageVariableSetting.stub(:new).with({'these' => 'params'}) { mock_page_variable_setting(:save => true) }
        post :create, :page_variable_setting => {'these' => 'params'}
        assigns(:page_variable_setting).should be(mock_page_variable_setting)
      end

      it "redirects to the created page_variable_setting" do
        PageVariableSetting.stub(:new) { mock_page_variable_setting(:save => true) }
        post :create, :page_variable_setting => {}
        response.should redirect_to(page_variable_setting_url(mock_page_variable_setting))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved page_variable_setting as @page_variable_setting" do
        PageVariableSetting.stub(:new).with({'these' => 'params'}) { mock_page_variable_setting(:save => false) }
        post :create, :page_variable_setting => {'these' => 'params'}
        assigns(:page_variable_setting).should be(mock_page_variable_setting)
      end

      it "re-renders the 'new' template" do
        PageVariableSetting.stub(:new) { mock_page_variable_setting(:save => false) }
        post :create, :page_variable_setting => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested page_variable_setting" do
        PageVariableSetting.stub(:find).with("37") { mock_page_variable_setting }
        mock_page_variable_setting.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :page_variable_setting => {'these' => 'params'}
      end

      it "assigns the requested page_variable_setting as @page_variable_setting" do
        PageVariableSetting.stub(:find) { mock_page_variable_setting(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:page_variable_setting).should be(mock_page_variable_setting)
      end

      it "redirects to the page_variable_setting" do
        PageVariableSetting.stub(:find) { mock_page_variable_setting(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(page_variable_setting_url(mock_page_variable_setting))
      end
    end

    describe "with invalid params" do
      it "assigns the page_variable_setting as @page_variable_setting" do
        PageVariableSetting.stub(:find) { mock_page_variable_setting(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:page_variable_setting).should be(mock_page_variable_setting)
      end

      it "re-renders the 'edit' template" do
        PageVariableSetting.stub(:find) { mock_page_variable_setting(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested page_variable_setting" do
      PageVariableSetting.stub(:find).with("37") { mock_page_variable_setting }
      mock_page_variable_setting.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the page_variable_settings list" do
      PageVariableSetting.stub(:find) { mock_page_variable_setting }
      delete :destroy, :id => "1"
      response.should redirect_to(page_variable_settings_url)
    end
  end

end
