require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe UserDetailSettingsController do

  def mock_user_detail_setting(stubs={})
    @mock_user_detail_setting ||= mock_model(UserDetailSetting, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all user_detail_settings as @user_detail_settings" do
      UserDetailSetting.stub(:all) { [mock_user_detail_setting] }
      get :index
      assigns(:user_detail_settings).should eq([mock_user_detail_setting])
    end
  end

  describe "GET show" do
    it "assigns the requested user_detail_setting as @user_detail_setting" do
      UserDetailSetting.stub(:find).with("37") { mock_user_detail_setting }
      get :show, :id => "37"
      assigns(:user_detail_setting).should be(mock_user_detail_setting)
    end
  end

  describe "GET new" do
    it "assigns a new user_detail_setting as @user_detail_setting" do
      UserDetailSetting.stub(:new) { mock_user_detail_setting }
      get :new
      assigns(:user_detail_setting).should be(mock_user_detail_setting)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_detail_setting as @user_detail_setting" do
      UserDetailSetting.stub(:find).with("37") { mock_user_detail_setting }
      get :edit, :id => "37"
      assigns(:user_detail_setting).should be(mock_user_detail_setting)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created user_detail_setting as @user_detail_setting" do
        UserDetailSetting.stub(:new).with({'these' => 'params'}) { mock_user_detail_setting(:save => true) }
        post :create, :user_detail_setting => {'these' => 'params'}
        assigns(:user_detail_setting).should be(mock_user_detail_setting)
      end

      it "redirects to the created user_detail_setting" do
        UserDetailSetting.stub(:new) { mock_user_detail_setting(:save => true) }
        post :create, :user_detail_setting => {}
        response.should redirect_to(user_detail_setting_url(mock_user_detail_setting))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_detail_setting as @user_detail_setting" do
        UserDetailSetting.stub(:new).with({'these' => 'params'}) { mock_user_detail_setting(:save => false) }
        post :create, :user_detail_setting => {'these' => 'params'}
        assigns(:user_detail_setting).should be(mock_user_detail_setting)
      end

      it "re-renders the 'new' template" do
        UserDetailSetting.stub(:new) { mock_user_detail_setting(:save => false) }
        post :create, :user_detail_setting => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_detail_setting" do
        UserDetailSetting.stub(:find).with("37") { mock_user_detail_setting }
        mock_user_detail_setting.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :user_detail_setting => {'these' => 'params'}
      end

      it "assigns the requested user_detail_setting as @user_detail_setting" do
        UserDetailSetting.stub(:find) { mock_user_detail_setting(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:user_detail_setting).should be(mock_user_detail_setting)
      end

      it "redirects to the user_detail_setting" do
        UserDetailSetting.stub(:find) { mock_user_detail_setting(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(user_detail_setting_url(mock_user_detail_setting))
      end
    end

    describe "with invalid params" do
      it "assigns the user_detail_setting as @user_detail_setting" do
        UserDetailSetting.stub(:find) { mock_user_detail_setting(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:user_detail_setting).should be(mock_user_detail_setting)
      end

      it "re-renders the 'edit' template" do
        UserDetailSetting.stub(:find) { mock_user_detail_setting(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_detail_setting" do
      UserDetailSetting.stub(:find).with("37") { mock_user_detail_setting }
      mock_user_detail_setting.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the user_detail_settings list" do
      UserDetailSetting.stub(:find) { mock_user_detail_setting }
      delete :destroy, :id => "1"
      response.should redirect_to(user_detail_settings_url)
    end
  end

end
