require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ViewConditionsController do

  def mock_view_condition(stubs={})
    @mock_view_condition ||= mock_model(ViewCondition, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all view_conditions as @view_conditions" do
      ViewCondition.stub(:all) { [mock_view_condition] }
      get :index
      assigns(:view_conditions).should eq([mock_view_condition])
    end
  end

  describe "GET show" do
    it "assigns the requested view_condition as @view_condition" do
      ViewCondition.stub(:find).with("37") { mock_view_condition }
      get :show, :id => "37"
      assigns(:view_condition).should be(mock_view_condition)
    end
  end

  describe "GET new" do
    it "assigns a new view_condition as @view_condition" do
      ViewCondition.stub(:new) { mock_view_condition }
      get :new
      assigns(:view_condition).should be(mock_view_condition)
    end
  end

  describe "GET edit" do
    it "assigns the requested view_condition as @view_condition" do
      ViewCondition.stub(:find).with("37") { mock_view_condition }
      get :edit, :id => "37"
      assigns(:view_condition).should be(mock_view_condition)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created view_condition as @view_condition" do
        ViewCondition.stub(:new).with({'these' => 'params'}) { mock_view_condition(:save => true) }
        post :create, :view_condition => {'these' => 'params'}
        assigns(:view_condition).should be(mock_view_condition)
      end

      it "redirects to the created view_condition" do
        ViewCondition.stub(:new) { mock_view_condition(:save => true) }
        post :create, :view_condition => {}
        response.should redirect_to(view_condition_url(mock_view_condition))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved view_condition as @view_condition" do
        ViewCondition.stub(:new).with({'these' => 'params'}) { mock_view_condition(:save => false) }
        post :create, :view_condition => {'these' => 'params'}
        assigns(:view_condition).should be(mock_view_condition)
      end

      it "re-renders the 'new' template" do
        ViewCondition.stub(:new) { mock_view_condition(:save => false) }
        post :create, :view_condition => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested view_condition" do
        ViewCondition.stub(:find).with("37") { mock_view_condition }
        mock_view_condition.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :view_condition => {'these' => 'params'}
      end

      it "assigns the requested view_condition as @view_condition" do
        ViewCondition.stub(:find) { mock_view_condition(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:view_condition).should be(mock_view_condition)
      end

      it "redirects to the view_condition" do
        ViewCondition.stub(:find) { mock_view_condition(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(view_condition_url(mock_view_condition))
      end
    end

    describe "with invalid params" do
      it "assigns the view_condition as @view_condition" do
        ViewCondition.stub(:find) { mock_view_condition(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:view_condition).should be(mock_view_condition)
      end

      it "re-renders the 'edit' template" do
        ViewCondition.stub(:find) { mock_view_condition(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested view_condition" do
      ViewCondition.stub(:find).with("37") { mock_view_condition }
      mock_view_condition.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the view_conditions list" do
      ViewCondition.stub(:find) { mock_view_condition }
      delete :destroy, :id => "1"
      response.should redirect_to(view_conditions_url)
    end
  end

end
